version: '3'
services:
  node:
    image: node:9.8.0
    volumes:
      - .:/project
    working_dir: /project
  http-server:
    image: node:9.8.0
    volumes:
      - .:/project
    working_dir: /project
    entrypoint: npm run http-server ./dist
